### ISSUE TITLE
Uncaught TypeError: key.indexOf is not a function

### ISSUE THREAD

**Issue by carsol** [mike-north/ember-orientation#8]
Hey Mike!

Trying this out for a small experimental project, I keep getting `Uncaught TypeError: key.indexOf is not a function` error on load. I've only installed the project via `ember install ember-orientation`.

I do see that the `orientation` service is hooked up but maybe something internal. I'm not sure, below is the error in the console.

<img width="1167" alt="screen shot 2015-08-28 at 8 41 29 am" src="https://cloud.githubusercontent.com/assets/1127090/9550506/a120d20e-4d60-11e5-98d2-cc7f7bf72c69.png">

Ember: 1.13.8

**Comment by elwayman02** [comment]
@mike-north I'd imagine it might have something to do with the keylookups in [_calculateDeltas](https://github.com/mike-north/ember-orientation/blob/master/addon/services/device-orientation.js#L122)

Shouldn't that be a for-of instead of for-in? for-in for arrays can have some unforeseen consequences unless protected by hasOwnProperty.

**Comment by mike-north** [comment]
Thanks @carsol - fixed in 3db4609
